name: Release a new version in PyPI

on:
  push:
    branches:
      - "preproduction"

jobs:
  check-version:
    name: Check version of the released package

    runs-on: ubuntu-latest

    steps:
      - name: Read version from pyproject.toml
        id: pyproject_version
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: "pyproject.toml"
          field: "version"

      - name: Read version from vcpkg.json
        id: vcpkg_version
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "mini_face_oxidized/open_face_api/vcpkg.json"
          prop_path: "version"

  publish:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI

    needs:
      - build

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://test.pypi.org/p/mini-face-oxidized

    permissions:
      id-token: write

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Download all the wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist/

      - name: Install dependencies
        run: |
          pip install twine

      - name: Publish distribution to Test PyPI
        run: |
          twine upload -r testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_KEY }}
